version: '3.8'

services:

  server_database:
    build:
      context: ./server_database
    ports:
      - "5432:5432"
    expose:
      - "5432"
    container_name: server_database

  server_go:
    build:
      context: ./server_go
    ports:
      - "8080:8080"
    container_name: server_go
    environment:
      - DATABASE_URL=server_database
    depends_on:
      - server_database


#Levanta el composer con docker-compose up --build